# Generated by Django 4.1.3 on 2022-11-16 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_driver', models.IntegerField(default=0)),
                ('product', models.CharField(max_length=50)),
                ('load_size', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=30, verbose_name='origin destination')),
                ('destination', models.CharField(max_length=30, verbose_name='final destination')),
                ('budget', models.CharField(max_length=10, verbose_name='estinate budget')),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
