# Generated by Django 4.1.3 on 2022-11-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='product_category',
            field=models.CharField(default=models.CharField(max_length=50), max_length=30),
        ),
    ]
