# Generated by Django 4.1.3 on 2022-11-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_user_image_curstomer_image_driver_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curstomer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='image',
        ),
    ]
